// Generated by tools/asset-ingest/environments.mjs — do not edit by hand.
//
// Re-run that script to change this list. Every environment here, and the
// reason it was chosen, is in the ENVIRONMENTS table at the top of it.
//
// 12 maps, 16.3 MB including previews, all conditioned to 1024px wide.

/**
 * A lighting environment a scene can be rendered under.
 *
 * ── Why the licence fields are on every one of these ────────────────────────
 * The set that ships today is entirely CC0, so nobody is owed a credit. That is
 * a fact about this list, not about the type — the moment one CC-BY sky is
 * added, an obligation exists and nothing about the render would reveal it.
 *
 * These four fields are deliberately the same shape as `AssetModel`, so an
 * environment can be handed to the credits path the moment that path learns to
 * ask about the scene's environment as well as its furniture. `creditsFor`
 * currently walks placed objects only, which means a credited HDRI would be
 * silently dropped today.
 */
export interface EnvironmentPreset {
  id: string
  name: string
  kind: EnvironmentKind
  /** Shown in the picker: what this light does, not where it was photographed. */
  note: string
  /** Equirectangular .hdr, conditioned to 1024px. What `scene.hdriUrl` stores. */
  url: string
  /** Tone-mapped preview for the picker. */
  thumbnail: string
  licence: string
  author: string
  source: string
  /**
   * Where the key light sits, measured from the shipped file. Null when the sky
   * is diffuse enough to have no key light — an overcast map has no sun, and
   * offering a direction for one would be inventing it.
   *
   * `elevation` is degrees above the horizon, and it is shadow length: a sun at
   * 29 degrees throws a shadow 1.8x the height of what casts it, one at 43
   * throws 1.07x. `azimuth` is degrees off the model's -Z, positive clockwise
   * seen from above.
   *
   * Measured rather than declared because two environments picked by eye and by
   * category turned out to be the same light 1.1 degrees apart, and no tag,
   * name or note revealed it.
   */
  sun: { elevation: number; azimuth: number } | null
  /** The one offered when a scene has never had an environment chosen. */
  isDefault?: boolean
}

export type EnvironmentKind =
  | "daylight"
  | "overcast"
  | "evening"
  | "night"
  | "urban"
  | "studio"

/** Group labels, in the order a picker should show them. */
export const ENVIRONMENT_KINDS: ReadonlyArray<{ id: EnvironmentKind; label: string }> = [
  { id: "daylight", label: "Daylight" },
  { id: "overcast", label: "Overcast" },
  { id: "evening", label: "Evening" },
  { id: "night", label: "Night" },
  { id: "urban", label: "Urban" },
  { id: "studio", label: "Studio" },
]

export const ENVIRONMENTS: readonly EnvironmentPreset[] = [
  {
    id: "partly-cloudy",
    name: "Partly cloudy midday",
    kind: "daylight",
    note: "Bright with soft-edged shadows. The safe default for most interiors.",
    url: "/env/partly-cloudy.hdr",
    thumbnail: "/env/partly-cloudy.jpg",
    licence: "CC0 1.0 Public Domain",
    author: "Greg Zaal, Jarod Guest",
    source: "https://polyhaven.com/a/kloofendal_48d_partly_cloudy_puresky",
    sun: { elevation: 48, azimuth: 34.3 },
    isDefault: true,
  },
  {
    id: "midday",
    name: "Midday sun",
    kind: "daylight",
    note: "Hard, high sun with short shadows. Shows off glazing and double-height space.",
    url: "/env/midday.hdr",
    thumbnail: "/env/midday.jpg",
    licence: "CC0 1.0 Public Domain",
    author: "Greg Zaal",
    source: "https://polyhaven.com/a/kloofendal_43d_clear_puresky",
    sun: { elevation: 43.1, azimuth: 36 },
  },
  {
    id: "afternoon",
    name: "Afternoon sun",
    kind: "daylight",
    note: "Low sun and long raking shadows across the floor.",
    url: "/env/afternoon.hdr",
    thumbnail: "/env/afternoon.jpg",
    licence: "CC0 1.0 Public Domain",
    author: "Jarod Guest, Sergej Majboroda",
    source: "https://polyhaven.com/a/autumn_field_puresky",
    sun: { elevation: 29, azimuth: 36.4 },
  },
  {
    id: "overcast",
    name: "Overcast",
    kind: "overcast",
    note: "Even, shadowless light. Use when the plan has no established orientation.",
    url: "/env/overcast.hdr",
    thumbnail: "/env/overcast.jpg",
    licence: "CC0 1.0 Public Domain",
    author: "Jarod Guest, Sergej Majboroda",
    source: "https://polyhaven.com/a/overcast_soil_puresky",
    sun: null,
  },
  {
    id: "soft-grey",
    name: "Soft grey",
    kind: "overcast",
    note: "The flattest light available. Reads shape and volume without drama.",
    url: "/env/soft-grey.hdr",
    thumbnail: "/env/soft-grey.jpg",
    licence: "CC0 1.0 Public Domain",
    author: "Sergey Rudavin, Jarod Guest",
    source: "https://polyhaven.com/a/mud_road_puresky",
    sun: null,
  },
  {
    id: "golden-hour",
    name: "Golden hour",
    kind: "evening",
    note: "Warm low sun. The usual choice for a hero shot.",
    url: "/env/golden-hour.hdr",
    thumbnail: "/env/golden-hour.jpg",
    licence: "CC0 1.0 Public Domain",
    author: "Greg Zaal, Jarod Guest",
    source: "https://polyhaven.com/a/kloppenheim_06_puresky",
    sun: { elevation: 4.7, azimuth: 40.6 },
  },
  {
    id: "sunset",
    name: "Sunset",
    kind: "evening",
    note: "Cooler dusk sky. Interior lighting reads as lit rather than washed out.",
    url: "/env/sunset.hdr",
    thumbnail: "/env/sunset.jpg",
    licence: "CC0 1.0 Public Domain",
    author: "Greg Zaal, Dimitrios Savva, Jarod Guest",
    source: "https://polyhaven.com/a/belfast_sunset_puresky",
    sun: { elevation: 1.9, azimuth: 37.8 },
  },
  {
    id: "moonlit",
    name: "Moonlit",
    kind: "night",
    note: "Dark and blue. Windows read as lit from within.",
    url: "/env/moonlit.hdr",
    thumbnail: "/env/moonlit.jpg",
    licence: "CC0 1.0 Public Domain",
    author: "Greg Zaal",
    source: "https://polyhaven.com/a/dikhololo_night",
    sun: { elevation: 0.9, azimuth: -57.1 },
  },
  {
    id: "night-sky",
    name: "Clear night",
    kind: "night",
    note: "Stars, with a warm lamp near the horizon.",
    url: "/env/night-sky.hdr",
    thumbnail: "/env/night-sky.jpg",
    licence: "CC0 1.0 Public Domain",
    author: "Greg Zaal",
    source: "https://polyhaven.com/a/satara_night",
    sun: { elevation: -3.7, azimuth: 43.4 },
  },
  {
    id: "city-overcast",
    name: "City, overcast",
    kind: "urban",
    note: "Towers and glass outside the window. For apartments, not villas.",
    url: "/env/city-overcast.hdr",
    thumbnail: "/env/city-overcast.jpg",
    licence: "CC0 1.0 Public Domain",
    author: "Andreas Mischok",
    source: "https://polyhaven.com/a/canary_wharf",
    sun: { elevation: 20.6, azimuth: 173.1 },
  },
  {
    id: "city-sun",
    name: "City, sunny",
    kind: "urban",
    note: "Street level, strong sun. For ground-floor and commercial frontage.",
    url: "/env/city-sun.hdr",
    thumbnail: "/env/city-sun.jpg",
    licence: "CC0 1.0 Public Domain",
    author: "Sergej Majboroda",
    source: "https://polyhaven.com/a/wide_street_01",
    sun: { elevation: 52.9, azimuth: 36 },
  },
  {
    id: "studio",
    name: "Studio",
    kind: "studio",
    note: "Neutral softboxes on white. For a single object, not a room.",
    url: "/env/studio.hdr",
    thumbnail: "/env/studio.jpg",
    licence: "CC0 1.0 Public Domain",
    author: "Sergej Majboroda",
    source: "https://polyhaven.com/a/studio_small_09",
    sun: { elevation: 14.9, azimuth: -148.2 },
  },
]

export const environmentById = (id: string): EnvironmentPreset | undefined =>
  ENVIRONMENTS.find((environment) => environment.id === id)

/** The environment matching a stored `scene.hdriUrl`, if it is one of ours. */
export const environmentByUrl = (url: string | null): EnvironmentPreset | undefined =>
  url ? ENVIRONMENTS.find((environment) => environment.url === url) : undefined

export const defaultEnvironment = (): EnvironmentPreset =>
  ENVIRONMENTS.find((environment) => environment.isDefault) ?? ENVIRONMENTS[0]
