// Generated by tools/asset-ingest/materials.mjs — do not edit by hand.
//
// Re-run that script to change this list. Every surface here, the material
// behind it and the reason for its tile size are in the SURFACES table at the
// top of it.
//
// 11 surfaces, 1448 KB total, all 512px.

import type { SurfaceKind } from '../plan/materials'

/**
 * Real photographed maps for one surface kind.
 *
 * ── These do not replace the procedural maps ────────────────────────────────
 * `plan/materials.ts` keeps drawing every surface on a canvas, and should. That
 * tier is what the headless geometry tests run against, what renders on the
 * first frame before anything has downloaded, and what a surface falls back to
 * when a map fails to load. This is a fourth tier layered on top, exactly as
 * `catalogue/models.ts` layers real GLBs over the parametric shapes.
 *
 * `surface(kind)` returns one cached material per kind, shared by every mesh
 * using it, so an upgrade assigns these three maps to that single instance and
 * every wall in the scene changes at once.
 *
 * ── All three maps must share one repeat ────────────────────────────────────
 * They describe the same surface. If the colour tiles at a different rate from
 * the normal, the grain and the relief drift apart across a wall — which looks
 * like nothing in particular and is very hard to trace back. `materials.ts`
 * already says this about its own maps; it is no less true of these.
 */
export interface SurfaceMaps {
  id: SurfaceKind
  name: string
  note: string
  /**
   * How much of the world one tile covers, in metres.
   *
   * ── Why this is a stored number and not a property of the image ──────────
   * ambientCG declares `dimensionX/Y/Z` in its API and leaves them at zero —
   * none of fifteen sampled materials had a real size — and two attempts to
   * recover the scale from the pixels are recorded as failures in
   * condition_material.py. So it is set by eye against a metre rule, once per
   * material.
   *
   * Set the repeat from this and the surface's real extent, never from a
   * constant: a floor whose planks change size between rooms is instantly
   * wrong, and that is what a fixed repeat produces.
   */
  tileMetres: number
  /** Albedo. sRGB — it is colour and must be decoded. */
  map: string
  /** Linear. Roughness is data; decoding it makes every surface too smooth. */
  roughnessMap: string
  /**
   * Linear, OpenGL convention.
   *
   * ambientCG ships NormalGL and NormalDX, identical but for an inverted green
   * channel. glTF and three.js are OpenGL, so DX is silently wrong: every bump
   * becomes a dent lit from the wrong side, and no summary statistic
   * distinguishes them — measured on one material, the two differ by 58 mean
   * levels in green while their green MEANS are 127.4 and 127.6. The ingest
   * tool refuses to substitute one for the other.
   */
  normalMap: string
  licence: string
  author: string
  source: string
}

export const SURFACE_MAPS: readonly SurfaceMaps[] = [
  {
    id: "floor-wood",
    name: "Oak boards",
    note: "Warm mid-oak, running bond.",
    tileMetres: 2,
    map: "/surfaces/floor-wood-color.jpg",
    roughnessMap: "/surfaces/floor-wood-roughness.jpg",
    normalMap: "/surfaces/floor-wood-normal.jpg",
    licence: "CC0 1.0 Public Domain",
    author: "ambientCG",
    source: "https://ambientcg.com/view?id=WoodFloor007",
  },
  {
    id: "floor-tile",
    name: "Grey floor tile",
    note: "Large-format grey porcelain, running bond.",
    tileMetres: 2,
    map: "/surfaces/floor-tile-color.jpg",
    roughnessMap: "/surfaces/floor-tile-roughness.jpg",
    normalMap: "/surfaces/floor-tile-normal.jpg",
    licence: "CC0 1.0 Public Domain",
    author: "ambientCG",
    source: "https://ambientcg.com/view?id=Tiles010",
  },
  {
    id: "wall",
    name: "Plaster",
    note: "Clean off-white plaster.",
    tileMetres: 2,
    map: "/surfaces/wall-color.jpg",
    roughnessMap: "/surfaces/wall-roughness.jpg",
    normalMap: "/surfaces/wall-normal.jpg",
    licence: "CC0 1.0 Public Domain",
    author: "ambientCG",
    source: "https://ambientcg.com/view?id=Plaster001",
  },
  {
    id: "ceiling",
    name: "Plaster ceiling",
    note: "The same plaster, tinted lighter.",
    tileMetres: 2,
    map: "/surfaces/ceiling-color.jpg",
    roughnessMap: "/surfaces/ceiling-roughness.jpg",
    normalMap: "/surfaces/ceiling-normal.jpg",
    licence: "CC0 1.0 Public Domain",
    author: "ambientCG",
    source: "https://ambientcg.com/view?id=Plaster001",
  },
  {
    id: "fabric",
    name: "Woven upholstery",
    note: "Grey woven upholstery.",
    tileMetres: 0.5,
    map: "/surfaces/fabric-color.jpg",
    roughnessMap: "/surfaces/fabric-roughness.jpg",
    normalMap: "/surfaces/fabric-normal.jpg",
    licence: "CC0 1.0 Public Domain",
    author: "ambientCG",
    source: "https://ambientcg.com/view?id=Fabric030",
  },
  {
    id: "wood",
    name: "Oak",
    note: "Warm timber for furniture bodies.",
    tileMetres: 1,
    map: "/surfaces/wood-color.jpg",
    roughnessMap: "/surfaces/wood-roughness.jpg",
    normalMap: "/surfaces/wood-normal.jpg",
    licence: "CC0 1.0 Public Domain",
    author: "ambientCG",
    source: "https://ambientcg.com/view?id=Wood005",
  },
  {
    id: "stone",
    name: "Marble",
    note: "Dark marble with white veining, for counters and sills.",
    tileMetres: 2,
    map: "/surfaces/stone-color.jpg",
    roughnessMap: "/surfaces/stone-roughness.jpg",
    normalMap: "/surfaces/stone-normal.jpg",
    licence: "CC0 1.0 Public Domain",
    author: "ambientCG",
    source: "https://ambientcg.com/view?id=Marble016",
  },
  {
    id: "paving",
    name: "Paving",
    note: "Grey linear pavers for a terrace or a pool surround.",
    tileMetres: 2,
    map: "/surfaces/paving-color.jpg",
    roughnessMap: "/surfaces/paving-roughness.jpg",
    normalMap: "/surfaces/paving-normal.jpg",
    licence: "CC0 1.0 Public Domain",
    author: "ambientCG",
    source: "https://ambientcg.com/view?id=PavingStones126A",
  },
  {
    id: "brick",
    name: "Brickwork",
    note: "Clean red brick in running bond, for exposed work.",
    tileMetres: 0.9,
    map: "/surfaces/brick-color.jpg",
    roughnessMap: "/surfaces/brick-roughness.jpg",
    normalMap: "/surfaces/brick-normal.jpg",
    licence: "CC0 1.0 Public Domain",
    author: "ambientCG",
    source: "https://ambientcg.com/view?id=Bricks005",
  },
  {
    id: "concrete",
    name: "Fair-faced concrete",
    note: "Smooth mid-grey concrete.",
    tileMetres: 2,
    map: "/surfaces/concrete-color.jpg",
    roughnessMap: "/surfaces/concrete-roughness.jpg",
    normalMap: "/surfaces/concrete-normal.jpg",
    licence: "CC0 1.0 Public Domain",
    author: "ambientCG",
    source: "https://ambientcg.com/view?id=Concrete002",
  },
  {
    id: "metal",
    name: "Brushed steel",
    note: "Brushed steel for appliances and fixtures.",
    tileMetres: 0.5,
    map: "/surfaces/metal-color.jpg",
    roughnessMap: "/surfaces/metal-roughness.jpg",
    normalMap: "/surfaces/metal-normal.jpg",
    licence: "CC0 1.0 Public Domain",
    author: "ambientCG",
    source: "https://ambientcg.com/view?id=Metal010",
  },
]

export const surfaceMapsFor = (kind: SurfaceKind): SurfaceMaps | undefined =>
  SURFACE_MAPS.find((surface) => surface.id === kind)

/**
 * Surface kinds that stay procedural, and why.
 *
 * Recorded because an absence and a decision look identical in a generated
 * file, and only one of them should survive review.
 */
export const PROCEDURAL_SURFACES: Readonly<Record<string, string>> = {
  water: "What makes water read as water is seeing THROUGH it to a floor that is the wrong colour and the wrong distance away. A photograph of water is a photograph of whatever was under it, pinned flat.",
  grass: "The hub has no grass — its texture harvest was filtered to interiors, the same decision that left it with 301 indoor HDRIs and no skies. A photographed lawn is the better answer and is one `hub.mjs fetch ambientcg:Grass###` away; the procedural turf is the honest stand-in until someone takes it.",
  glass: "Transparency, IOR and near-zero roughness are shader properties. A photograph of glass is a photograph of whatever was behind it.",
  plant: "Foliage colour varies per placement and the model carries its own leaves.",
  white: "A flat tint, deliberately. A texture here would only add noise to the one surface meant to have none.",
}
