# generated by datamodel-codegen:
#   filename:  building-1.json

from __future__ import annotations

from enum import Enum, StrEnum
from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Kind(StrEnum):
    text = 'text'
    mtext = 'mtext'
    dimension = 'dimension'
    roomTag = 'roomTag'
    levelMarker = 'levelMarker'
    title = 'title'
    north = 'north'


class Axis(StrEnum):
    x = 'x'
    y = 'y'
    aligned = 'aligned'
    radial = 'radial'


class Status(StrEnum):
    surveying = 'surveying'
    needs_unit = 'needs-unit'
    needs_frames = 'needs-frames'
    needs_levels = 'needs-levels'
    needs_review = 'needs-review'
    ready = 'ready'
    stale = 'stale'


class Profile(StrEnum):
    rect = 'rect'
    round = 'round'


class Alternative(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    label: str
    score: float


class Confidence(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    alternatives: list[Alternative] | None = None
    margin: float
    score: float


class Anchor(StrEnum):
    centre = 'centre'
    base_centre = 'base-centre'
    insert_point = 'insert-point'


class Licence(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    author: str
    source: str
    spdx: str


class Source(StrEnum):
    dxf_block = 'dxf-block'
    catalogue = 'catalogue'
    glb = 'glb'


class Emitter(StrEnum):
    facePair = 'facePair'
    perimeterTrace = 'perimeterTrace'
    blockSized = 'blockSized'
    blockHint = 'blockHint'
    rasterGap = 'rasterGap'
    rasterRegion = 'rasterRegion'
    dimension = 'dimension'
    mtext = 'mtext'
    ocr = 'ocr'
    openingCluster = 'openingCluster'
    stackPrior = 'stackPrior'
    ifcElement = 'ifcElement'
    default = 'default'
    user = 'user'


class Ref(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    bbox: Annotated[list[float] | None, Field(max_length=4, min_length=4)] = None
    block: str | None = None
    blockPath: list[str] | None = None
    entity: str | None = None
    handle: str | None = None
    index: float | None = None
    layer: str | None = None
    page: float | None = None


class Anchor1(StrEnum):
    floor = 'floor'
    wall = 'wall'
    in_wall = 'in-wall'
    ceiling = 'ceiling'


class Kind1(StrEnum):
    plan = 'plan'
    section = 'section'
    elevation = 'elevation'
    detail = 'detail'
    site = 'site'
    titleblock = 'titleblock'
    unknown = 'unknown'


class Id(RootModel[str]):
    root: str


class M(RootModel[float]):
    root: Annotated[
        float,
        Field(
            description="Derived from provenance so a re-import diffs instead of duplicating: 'w:dxf:LATEST#2F3A' | 'w:pair:s3-f0-0117' | 'op:blk:D750#41' | 'w:plan:v12-v13'"
        ),
    ]


class By(StrEnum):
    user = 'user'
    solver = 'solver'


class Op(StrEnum):
    setUnit = 'setUnit'
    setLayerRole = 'setLayerRole'
    setFrameKind = 'setFrameKind'
    setWallRole = 'setWallRole'
    setSpaceKind = 'setSpaceKind'
    moveVertex = 'moveVertex'
    setStoreyElevation = 'setStoreyElevation'
    setRegistration = 'setRegistration'
    acceptAlternative = 'acceptAlternative'
    suppressElement = 'suppressElement'
    addWall = 'addWall'
    nameSpace = 'nameSpace'
    setOpeningKind = 'setOpeningKind'
    setOpeningHinge = 'setOpeningHinge'


class ModelPatch(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    at: str
    by: By
    op: Op
    target: Id
    value: Any


class Hinge(StrEnum):
    left = 'left'
    right = 'right'


class Panels(Enum):
    number_1 = 1
    number_2 = 2


class OpeningKind(StrEnum):
    door = 'door'
    double_door = 'double-door'
    window = 'window'
    glazing = 'glazing'
    opening = 'opening'
    arch = 'arch'


class P2(RootModel[list[M]]):
    root: Annotated[list[M], Field(max_length=2, min_length=2)]


class Rad(RootModel[float]):
    root: float


class Choice(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    label: str
    patch: ModelPatch


class Metric(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expected: float
    observed: float
    unit: str


class Severity(StrEnum):
    blocking = 'blocking'
    high = 'high'
    low = 'low'
    info = 'info'


class Targets(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    elementIds: list[Id]
    frameId: Id | None = None
    storeyId: Id | None = None


class ResidualCode(StrEnum):
    CONVERTER_DROPPED_MODELSPACE = 'CONVERTER_DROPPED_MODELSPACE'
    UNIT_AMBIGUOUS = 'UNIT_AMBIGUOUS'
    UNIT_CONFLICT = 'UNIT_CONFLICT'
    NO_FRAMES = 'NO_FRAMES'
    FRAME_KIND_UNKNOWN = 'FRAME_KIND_UNKNOWN'
    STOREY_UNREGISTERED = 'STOREY_UNREGISTERED'
    OPEN_CYCLE = 'OPEN_CYCLE'
    NO_PERIMETER = 'NO_PERIMETER'
    WALL_OR_RAILING = 'WALL_OR_RAILING'
    WALL_CONFLICT = 'WALL_CONFLICT'
    OPENING_ORPHAN = 'OPENING_ORPHAN'
    SPACE_MERGED = 'SPACE_MERGED'
    DIM_CONFLICT = 'DIM_CONFLICT'
    DIM_AGREEMENT_LOW = 'DIM_AGREEMENT_LOW'
    CURVE_CHORDED = 'CURVE_CHORDED'
    BLOCK_GEOMETRY_HIDDEN = 'BLOCK_GEOMETRY_HIDDEN'
    LAYER_UNCHOSEN = 'LAYER_UNCHOSEN'
    SOLVER_DIVERGED = 'SOLVER_DIVERGED'
    GEOMETRY_DEGRADED = 'GEOMETRY_DEGRADED'
    UNVERIFIED = 'UNVERIFIED'


class Form(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['flat']


class Keep(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    n: P2
    p: P2


class Form1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    keep: Keep
    type: Literal['clip']


class Feature(StrEnum):
    pool = 'pool'
    deck = 'deck'
    lawn = 'lawn'
    path = 'path'
    road = 'road'
    planting = 'planting'
    compound_wall = 'compound-wall'


class Function(StrEnum):
    floor = 'floor'
    terrace = 'terrace'
    deck = 'deck'
    landing = 'landing'
    plinth = 'plinth'


class Mode(StrEnum):
    contour = 'contour'
    hull = 'hull'
    rooms = 'rooms'


class SourceKind(StrEnum):
    dwg = 'dwg'
    dxf = 'dxf'
    pdf_vector = 'pdf-vector'
    pdf_raster = 'pdf-raster'
    raster = 'raster'
    ifc = 'ifc'
    human = 'human'


class Converter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    args: list[str]
    modelSpaceEntities: float
    tool: Literal['libredwg']
    version: str


class SourceRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    bytes: float
    converter: Converter | None = None
    id: Id
    kind: SourceKind
    page: float | None = None
    sha256: str
    storageKey: str
    warnings: list[str]


class BoundedByItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    s0: M
    s1: M
    wallId: Id


class DerivedFrom(StrEnum):
    graph_cycle = 'graph-cycle'
    solid_interior_ring = 'solid-interior-ring'
    raster_region = 'raster-region'
    manual = 'manual'


class Kind2(StrEnum):
    room = 'room'
    wet = 'wet'
    circulation = 'circulation'
    service = 'service'
    outdoor = 'outdoor'
    shaft = 'shaft'
    fitting = 'fitting'


class Span1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    to: P2


class Span2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    bulge: float
    to: P2


class Span3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ccw: bool
    large: bool
    r: M
    to: P2


class Span(RootModel[Span1 | Span2 | Span3]):
    root: Span1 | Span2 | Span3


class Accepted(StrEnum):
    auto = 'auto'
    user = 'user'
    pending = 'pending'


class Method(StrEnum):
    stacking = 'stacking'
    maskCorrelation = 'maskCorrelation'
    annotation = 'annotation'
    user = 'user'
    none = 'none'


class Registration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accepted: Accepted
    against: Id | None
    method: Method
    offset: P2
    peak: float
    runnerUp: float


class Kind3(StrEnum):
    stair = 'stair'
    lift = 'lift'
    void = 'void'
    duct = 'duct'
    atrium = 'atrium'


class Unit(StrEnum):
    m = 'm'
    mm = 'mm'
    cm = 'cm'
    in_ = 'in'
    ft = 'ft'


class Agreement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    conflict: bool
    dimension: Unit | None
    wallThickness: Unit | None


class Candidate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    extent: M
    label: str
    scale: float
    suggested: bool


class DecidedBy(StrEnum):
    dimension = 'dimension'
    wallThickness = 'wallThickness'
    printedRoomSize = 'printedRoomSize'
    header = 'header'
    extent = 'extent'
    user = 'user'


class Posterior(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cm: float
    ft: float
    in_: Annotated[float, Field(alias='in')]
    m: float
    mm: float


class UnitDecision(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agreement: Agreement
    candidates: list[Candidate]
    decidedBy: DecidedBy
    margin: float
    posterior: Posterior
    scale: float
    unit: Unit


class Vertex(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Id
    pinned: bool | None = None
    sigma: M | None = None
    x: M
    y: M


class Align(StrEnum):
    centre = 'centre'
    left = 'left'
    right = 'right'


class Base(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    offset: M
    storeyId: Id


class WallRole(StrEnum):
    masonry = 'masonry'
    partition = 'partition'
    perimeter = 'perimeter'
    parapet = 'parapet'
    railing = 'railing'
    kerb = 'kerb'
    rejected = 'rejected'


class Measure(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    axis: Axis
    from_: Annotated[P2, Field(alias='from')]
    overridden: bool
    to: P2
    value: M


class Axis1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    theta: Rad
    weight: float


class Quality(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    blocking: float
    closedSpaceFraction: float
    dimAgreement: float | None
    dimSamples: float
    meanWallResidual: M
    mitreFallbacks: float
    openingsUnassigned: float
    solved: bool
    unitMargin: float
    unpairedRuns: float


class Curve2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    closed: bool | None = None
    spans: list[Span]
    start: P2


class OpeningSpec(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    height: M
    kind: OpeningKind
    width: M


class Size(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    depth: M
    height: M
    width: M


class Definition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    anchor: Anchor
    catalogueItem: str | None = None
    id: Id
    licence: Annotated[
        Licence | None,
        Field(
            description='REQUIRED whenever meshUrl is set. Copy the CONSTRAINT from apps/studio/src/catalogue/types.ts:86 — it is what makes CC-BY compliance structurally impossible to forget.'
        ),
    ] = None
    meshUrl: str | None = None
    name: str
    openingSpec: OpeningSpec | None = None
    size: Size
    source: Source
    yaw: Rad


class Evidence(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    emitter: Emitter
    ref: Ref | None = None
    src: Id
    weight: float


class Frame(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    bboxSource: Annotated[list[float], Field(max_length=4, min_length=4)]
    entityCount: float
    id: Id
    kind: Kind1
    source: Id
    storeyId: Id | None
    title: str | None = None
    unitId: Id | None
    wallLength: M


class Measured(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    evidence: list[Evidence]
    residual: float | None = None
    sigma: float
    value: float


class Profile1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    poly: list[P2]


class Provenance(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    confidence: Confidence
    locked: bool
    primary: Evidence
    suppressed: bool | None = None


class Residual(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    choices: list[Choice] | None = None
    code: ResidualCode
    id: Id
    message: str
    metric: Metric | None
    severity: Severity
    targets: Targets


class Roof(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    form: Form | Form1
    holes: list[Curve2]
    id: Id
    outline: Curve2
    overhang: M
    provenance: Provenance
    thickness: M


class SiteFeature(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    depth: M | None = None
    feature: Feature
    holes: list[Curve2]
    id: Id
    outline: Curve2
    provenance: Provenance
    z: M | None = None


class Slab(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    function: Function
    holes: list[Curve2]
    id: Id
    mode: Mode
    outline: Curve2
    provenance: Provenance
    thickness: M
    topOffset: M


class Name(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    provenance: Provenance
    value: str | None


class Space(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    alsoNamed: list[str] | None = None
    area: M
    boundary: Curve2
    boundedBy: Annotated[
        list[BoundedByItem],
        Field(
            description='WHICH STRETCH of which wall faces this room. This is the topology the planar graph only implies, and it is what lets skirting be cut at a doorway (buildGeometry.ts:373 currently runs straight through one).'
        ),
    ]
    ceiling: Measured
    derivedFrom: DerivedFrom
    holes: list[Curve2]
    id: Id
    kind: Kind2
    loop: list[Id]
    name: Name
    printedSize: Annotated[list[M] | None, Field(max_length=2, min_length=2)] = None
    provenance: Provenance


class Footprint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    area: M
    mode: Mode
    outline: Curve2


class StoreyLink(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fromStoreyId: Id
    id: Id
    kind: Kind3
    polygon: Curve2
    toStoreyId: Id


class Wall(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    a: Id
    align: Align
    axisFamily: float | None
    b: Id
    base: Base
    baseline: Curve2
    height: Measured
    id: Id
    layer: str | None = None
    openingIds: list[Id]
    paired: bool
    provenance: Provenance
    role: WallRole
    stackedWith: list[Id] | None = None
    thickness: Measured


class Annotation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    at: P2
    frameId: Id | None = None
    id: Id
    kind: Kind
    measure: Measure | None = None
    provenance: Provenance
    refersTo: Id | None = None
    rotation: Rad | None = None
    storeyId: Id | None = None
    text: str
    textHeight: M | None = None


class Column(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    at: P2
    base: Base
    height: M
    id: Id
    profile: Profile
    provenance: Provenance
    size: Annotated[list[M], Field(max_length=2, min_length=2)]
    yaw: Rad


class Fixture(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    anchor: Anchor1 | None = None
    at: P2
    customUrl: str | None = None
    definitionId: Id
    hostWallId: Id | None = None
    id: Id
    mirrored: bool | None = None
    provenance: Provenance
    size: Size | None = None
    yaw: Rad
    z: M


class Opening(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    along: M
    definitionId: Id | None = None
    head: Measured
    hinge: Hinge | None = None
    id: Id
    kind: OpeningKind
    panels: Panels | None = None
    profile: Literal['rect'] | Literal['arch'] | Profile1
    provenance: Provenance
    reveal: M
    sill: Measured
    swing: Rad | None = None
    wallId: Id | None
    width: Measured


class Storey(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    axes: list[Axis1]
    clearHeight: Measured
    columns: dict[str, Column]
    elevation: Measured
    fixtures: dict[str, Fixture]
    floorToFloor: Measured
    footprint: Footprint | None
    frames: list[Id]
    id: Id
    index: Annotated[
        float,
        Field(
            description='CANONICAL order from title text, never sheet y. One real sheet ascends and another descends; ordering by y stacks half the villas upside down.'
        ),
    ]
    name: str
    openings: dict[str, Opening]
    reconstructed: str | None
    registration: Annotated[
        Registration | None,
        Field(
            description='THE MARGIN IS THE CONFIDENCE. build_villas.py:350 prints peak and runner-up; here it is data, and below 1.25x it becomes a question, never an auto-accept.'
        ),
    ]
    roofs: dict[str, Roof]
    site: dict[str, SiteFeature]
    slabThickness: Measured
    slabs: dict[str, Slab]
    spaces: list[Space]
    vertices: dict[str, Vertex]
    walls: dict[str, Wall]


class BuildingModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    annotations: list[Annotation]
    definitions: dict[str, Definition]
    frames: list[Frame]
    id: Id
    name: str
    northAngle: Rad
    patches: list[ModelPatch]
    quality: Quality
    residuals: list[Residual]
    schema_: Annotated[Literal['arcvia.building/1'], Field(alias='schema')]
    sourceOrigin: Annotated[
        dict[str, P2],
        Field(
            description="Subtracted ONCE PER SOURCE, not per frame. Shifting each frame to its own min-corner destroys exactly the relative alignment that storey registration exists to recover — the contradiction that made a rival design's registration stage unreachable."
        ),
    ]
    sources: list[SourceRef]
    status: Status
    storeyLinks: list[StoreyLink]
    storeys: list[Storey]
    unit: UnitDecision
    units: Literal['m']
    up: Literal['z']


class Model(RootModel[BuildingModel]):
    root: BuildingModel
